import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useState } from 'react'
import toast from 'react-hot-toast'
import { SectionCard } from '../Shared/SectionCard'
import {
  createMock,
  deleteMock,
  exportMocksOpenApi,
  exportMocksPostman,
  getMocks,
} from '../../services/devdashApi'

function downloadBlob(blob: Blob, fileName: string) {
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = fileName
  anchor.click()
  URL.revokeObjectURL(url)
}

export function APIMockerView() {
  const [route, setRoute] = useState('/api/users')
  const [method, setMethod] = useState('GET')
  const [statusCode, setStatusCode] = useState(200)
  const [delayMs, setDelayMs] = useState(200)
  const queryClient = useQueryClient()

  const mocksQuery = useQuery({
    queryKey: ['mocks'],
    queryFn: getMocks,
    retry: false,
  })

  const createMutation = useMutation({
    mutationFn: createMock,
    onSuccess: async () => {
      await queryClient.invalidateQueries({ queryKey: ['mocks'] })
      toast.success('Mock endpoint created')
    },
  })

  const deleteMutation = useMutation({
    mutationFn: deleteMock,
    onSuccess: async () => {
      await queryClient.invalidateQueries({ queryKey: ['mocks'] })
      toast.success('Mock endpoint removed')
    },
  })

  const openApiExportMutation = useMutation({
    mutationFn: exportMocksOpenApi,
    onSuccess: (blob) => {
      downloadBlob(blob, 'devdash-openapi.json')
      toast.success('OpenAPI exported')
    },
  })

  const postmanExportMutation = useMutation({
    mutationFn: exportMocksPostman,
    onSuccess: (blob) => {
      downloadBlob(blob, 'devdash-postman.json')
      toast.success('Postman collection exported')
    },
  })

  return (
    <div className="grid gap-4 lg:grid-cols-2">
      <SectionCard title="Endpoint Builder" subtitle="Create status, delay, and schema-backed mock responses">
        <div className="mb-3 grid gap-2 md:grid-cols-2">
          <input
            value={route}
            onChange={(event) => setRoute(event.target.value)}
            className="focus-ring rounded-lg border border-tn-border bg-tn-bg px-3 py-2 text-sm"
            placeholder="Route"
          />
          <input
            value={method}
            onChange={(event) => setMethod(event.target.value.toUpperCase())}
            className="focus-ring rounded-lg border border-tn-border bg-tn-bg px-3 py-2 text-sm"
            placeholder="Method"
          />
          <input
            type="number"
            value={statusCode}
            onChange={(event) => setStatusCode(Number(event.target.value))}
            className="focus-ring rounded-lg border border-tn-border bg-tn-bg px-3 py-2 text-sm"
            placeholder="Status code"
          />
          <input
            type="number"
            value={delayMs}
            onChange={(event) => setDelayMs(Number(event.target.value))}
            className="focus-ring rounded-lg border border-tn-border bg-tn-bg px-3 py-2 text-sm"
            placeholder="Delay (ms)"
          />
        </div>

        <button
          type="button"
          onClick={() =>
            createMutation.mutate({
              route,
              method,
              statusCode,
              delayMs,
              response: {
                ok: true,
                message: 'Generated by DevDash',
                timestamp: new Date().toISOString(),
              },
            })
          }
          className="focus-ring mb-3 rounded-lg border border-tn-blue/50 bg-tn-blue/10 px-3 py-2 text-sm text-tn-blue hover:bg-tn-blue/20"
        >
          Create Mock
        </button>

        <div className="mb-3 flex gap-2">
          <button
            type="button"
            onClick={() => openApiExportMutation.mutate()}
            className="focus-ring rounded-lg border border-tn-teal/40 px-3 py-2 text-xs text-tn-teal"
          >
            Export OpenAPI
          </button>
          <button
            type="button"
            onClick={() => postmanExportMutation.mutate()}
            className="focus-ring rounded-lg border border-tn-purple/40 px-3 py-2 text-xs text-tn-purple"
          >
            Export Postman
          </button>
        </div>

        <div className="space-y-2 font-mono text-sm">
          {mocksQuery.data?.map((mock) => (
            <div key={mock.id} className="flex items-center justify-between rounded-xl border border-tn-border bg-tn-bg px-3 py-2">
              <p className="text-tn-blue">
                {mock.method} {mock.route}
              </p>
              <button
                type="button"
                onClick={() => deleteMutation.mutate(mock.id)}
                className="focus-ring rounded-md border border-tn-coral/40 px-2 py-1 text-xs text-tn-coral"
              >
                Delete
              </button>
            </div>
          ))}
          {mocksQuery.isError ? <p className="text-xs text-tn-muted">Connect GitHub to manage API mocks.</p> : null}
        </div>
      </SectionCard>

      <SectionCard title="Test Console" subtitle="Terminal-style request/response output preview">
        <pre className="overflow-x-auto rounded-xl border border-tn-border bg-[#131623] p-3 font-mono text-xs text-tn-teal">
{`$ curl https://mock.devdash.dev/v1/users
{
  "id": "usr_204",
  "username": "neon-coder",
  "status": "active"
}`}
        </pre>
      </SectionCard>
    </div>
  )
}
